export const mock_token =
"Bearer eyJhbGciOiJIUzI1NiJ9.eyJjYXRlZ29yeSI6ImFjY2VzcyIsImxvZ2luSWQiOiJrYW5ndGVhOSIsImlhdCI6MTcyNzQwMzAxNSwiZXhwIjoxNzI3NDAzNjE1fQ.9du5ach5lnHKDpB8gJ0pKyYfBjtkxQy0RG8hZLPwE4Q"

